# Choose the version of dbt that will run the project.
# Supported versions are listed in https://fivetran.com/docs/transformations/dbt/setup-guide#prerequisites.
# If the version is not specified, dbt 0.18.0 will be used.
dbtVersion: 1.0.1

jobs:
  - name: daytime101
    schedule: 0 12 * * *
    steps:
      - name: run dummy
        command: dbt run -m dummy
      - name: run all
        command: dbt run
